[book]
authors = ["Michael Kirk", "Joshua Lund"]
language = "en"
multilingual = false
src = "src"
title = "Answering Geospatial Questions with Rust"

[output.html]
additional-css = ["assets/css/style.css"]
curly-quotes = true

[output.html.playground]
runnable = false
