[book]
authors = ["Michael Kirk", "Joshua Lund"]
language = "en"
src = "src"
title = "Geospatial Rust"

[output.html]
additional-css = ["assets/css/style.css"]
smart-punctuation = true

[output.html.playground]
runnable = false
