[package]
name = "cookbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.20.1"
proj = "0.26.0"
wkt = "0.10.1"

[patch.crates-io]
wkt = { git = "https://github.com/georust/wkt", branch = "release/0.10.1" }
